import { AppShell } from "@/components/app-shell";
import { CopyButton } from "@/components/copy-button";
import { createInviteCodeAction } from "@/lib/actions/admin";
import { requireAdmin } from "@/lib/auth";
import { getAppContext } from "@/lib/page-context";
import { createAdminClient } from "@/lib/supabase/admin";

export default async function AdminPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}) {
  await requireAdmin(); const {profile}=await getAppContext(); const q=await searchParams; const created=typeof q.created==="string"?q.created:""; const error=typeof q.error==="string"?q.error:""; const admin=createAdminClient(); const [{data:codes},{data:profiles}]=await Promise.all([admin.from("invite_codes").select("code,created_at,expires_at,used_by,used_at").order("created_at",{ascending:false}),admin.from("profiles").select("id,display_name")]);
  type InviteRow = { code:string; created_at:string; expires_at:string|null; used_by:string|null; used_at:string|null };
  type NameRow = { id:string; display_name:string };
  const typedCodes=(codes??[]) as InviteRow[]; const typedProfiles=(profiles??[]) as NameRow[]; const names=new Map(typedProfiles.map((p:NameRow)=>[p.id,p.display_name]));
  return <AppShell displayName={profile.display_name} isAdmin><div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Admin</p><h1 className="mt-3 text-4xl font-black tracking-[-.05em]">초대 코드 관리</h1></div><form action={createInviteCodeAction}><button className="primary-button">새 코드 발급</button></form></div>{created&&<div role="status" className="mt-6 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 font-bold text-[var(--success)]"><span>새 초대 코드: <strong className="tracking-wider">{created}</strong></span><CopyButton value={created}/></div>}{error&&<div role="alert" className="mt-6 rounded-2xl border border-red-200 bg-red-50 p-4 font-bold text-[var(--danger)]">{error}</div>}<div className="mt-8 overflow-hidden rounded-[1.8rem] border border-[var(--line)] bg-[var(--surface)]"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-[var(--surface-2)] text-xs uppercase tracking-wider text-[var(--muted)]"><tr><th className="px-5 py-4">코드</th><th className="px-5 py-4">상태</th><th className="px-5 py-4">사용자</th><th className="px-5 py-4">발급일</th><th className="px-5 py-4"></th></tr></thead><tbody>{typedCodes.map((c:InviteRow)=><tr key={c.code} className="border-t border-[var(--line)]"><td className="px-5 py-4 font-black tracking-wider">{c.code}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-extrabold ${c.used_by?"bg-zinc-100 text-zinc-500":"bg-emerald-50 text-[var(--success)]"}`}>{c.used_by?"사용 완료":"사용 가능"}</span></td><td className="px-5 py-4 font-bold">{c.used_by?names.get(c.used_by)??"가입 사용자":"—"}</td><td className="px-5 py-4 text-[var(--muted)]">{new Date(c.created_at).toLocaleDateString("ko-KR",{timeZone:"Asia/Seoul"})}</td><td className="px-5 py-4"><CopyButton value={c.code}/></td></tr>)}</tbody></table></div>{typedCodes.length===0&&<p className="p-8 text-center font-bold text-[var(--muted)]">발급된 코드가 없습니다.</p>}</div></div></AppShell>;
}
